export const country = [
  { alpha2Code: 'af', country: 'Afghanistan (افغانستان)', dialCode: '93' },
  { alpha2Code: 'al', country: 'Albania (Shqipëri)', dialCode: '355' },
  { alpha2Code: 'dz', country: 'Algeria (الجزائر‬‎)', dialCode: '213' },
  { alpha2Code: 'as', country: 'American Samoa', dialCode: '1684' },
  { alpha2Code: 'ad', country: 'Andorra', dialCode: '376' },
  { alpha2Code: 'ao', country: 'Angola', dialCode: '244' },
  { alpha2Code: 'ai', country: 'Anguilla', dialCode: '1264' },
  { alpha2Code: 'ag', country: 'Antigua and Barbuda', dialCode: '1268' },
  { alpha2Code: 'ar', country: 'Argentina', dialCode: '54' },
  { alpha2Code: 'am', country: 'Armenia (Հայաստան)', dialCode: '374' },
  { alpha2Code: 'aw', country: 'Aruba', dialCode: '297' },
  { alpha2Code: 'au', country: 'Australia', dialCode: '61' },
  { alpha2Code: 'at', country: 'Austria (Österreich)', dialCode: '43' },
  { alpha2Code: 'az', country: 'Azerbaijan (Azərbaycan)', dialCode: '994' },
  { alpha2Code: 'bs', country: 'Bahamas', dialCode: '1242' },
  { alpha2Code: 'bh', country: 'Bahrain (البحرين‬‎)', dialCode: '973' },
  { alpha2Code: 'bd', country: 'Bangladesh (বাংলাদেশ)', dialCode: '880' },
  { alpha2Code: 'bb', country: 'Barbados', dialCode: '1246' },
  { alpha2Code: 'by', country: 'Belarus (Беларусь)', dialCode: '375' },
  { alpha2Code: 'be', country: 'Belgium (België)', dialCode: '32' },
  { alpha2Code: 'bz', country: 'Belize', dialCode: '501' },
  { alpha2Code: 'bj', country: 'Benin (Bénin)', dialCode: '229' },
  { alpha2Code: 'bm', country: 'Bermuda', dialCode: '1441' },
  { alpha2Code: 'bt', country: 'Bhutan (འབྲུག)', dialCode: '975' },
  { alpha2Code: 'bo', country: 'Bolivia', dialCode: '591' },
  {
    alpha2Code: 'ba',
    country: 'Bosnia and Herzegovina (Босна и Херцеговина)',
    dialCode: '387',
  },
  { alpha2Code: 'bw', country: 'Botswana', dialCode: '267' },
  { alpha2Code: 'br', country: 'Brazil (Brasil)', dialCode: '55' },
  { alpha2Code: 'bn', country: 'Brunei', dialCode: '673' },
  { alpha2Code: 'bg', country: 'Bulgaria (България)', dialCode: '359' },
  { alpha2Code: 'bf', country: 'Burkina Faso', dialCode: '226' },
  { alpha2Code: 'bi', country: 'Burundi (Uburundi)', dialCode: '257' },
  { alpha2Code: 'kh', country: 'Cambodia (កម្ពុជា)', dialCode: '855' },
  { alpha2Code: 'cm', country: 'Cameroon (Cameroun)', dialCode: '237' },
  { alpha2Code: 'ca', country: 'Canada', dialCode: '1' },
  { alpha2Code: 'cv', country: 'Cape Verde (Kabu Verdi)', dialCode: '238' },
  { alpha2Code: 'ky', country: 'Cayman Islands', dialCode: '1345' },
  {
    alpha2Code: 'cf',
    country: 'Central African Republic (République centrafricaine)',
    dialCode: '236',
  },
  { alpha2Code: 'td', country: 'Chad (Tchad)', dialCode: '235' },
  { alpha2Code: 'cl', country: 'Chile', dialCode: '56' },
  { alpha2Code: 'cn', country: 'China (中国)', dialCode: '86' },
  { alpha2Code: 'co', country: 'Colombia', dialCode: '57' },
  { alpha2Code: 'km', country: 'Comoros (جزر القمر‬‎)', dialCode: '269' },
  {
    alpha2Code: 'cd',
    country: 'DR Congo (Jamhuri ya Kidemokrasia ya Kongo)',
    dialCode: '243',
  },
  {
    alpha2Code: 'cg',
    country: 'Congo (Republic) (Congo-Brazzaville)',
    dialCode: '242',
  },
  { alpha2Code: 'ck', country: 'Cook Islands', dialCode: '682' },
  { alpha2Code: 'cr', country: 'Costa Rica', dialCode: '506' },
  { alpha2Code: 'ci', country: "Côte d'Ivoire (Ivory Coast)", dialCode: '225' },
  { alpha2Code: 'hr', country: 'Croatia (Hrvatska)', dialCode: '385' },
  { alpha2Code: 'cu', country: 'Cuba', dialCode: '53' },
  { alpha2Code: 'cy', country: 'Cyprus (Κύπρος)', dialCode: '357' },
  {
    alpha2Code: 'cz',
    country: 'Czech Republic (Česká republika)',
    dialCode: '420',
  },
  { alpha2Code: 'dk', country: 'Denmark (Danmark)', dialCode: '45' },
  { alpha2Code: 'dj', country: 'Djibouti', dialCode: '253' },
  { alpha2Code: 'dm', country: 'Dominica', dialCode: '1767' },
  {
    alpha2Code: 'do',
    country: 'Dominican Republic (República Dominicana)',
    dialCode: '1',
  },
  { alpha2Code: 'tl', country: 'East Timor (Timor-Leste)', dialCode: '670' },
  { alpha2Code: 'ec', country: 'Ecuador', dialCode: '593' },
  { alpha2Code: 'eg', country: 'Egypt (مصر‬‎)', dialCode: '20' },
  { alpha2Code: 'sv', country: 'El Salvador', dialCode: '503' },
  {
    alpha2Code: 'gq',
    country: 'Equatorial Guinea (Guinea Ecuatorial)',
    dialCode: '240',
  },
  { alpha2Code: 'er', country: 'Eritrea', dialCode: '291' },
  { alpha2Code: 'ee', country: 'Estonia (Eesti)', dialCode: '372' },
  { alpha2Code: 'et', country: 'Ethiopia', dialCode: '251' },
  {
    alpha2Code: 'fk',
    country: 'Falkland Islands (Islas Malvinas)',
    dialCode: '500',
  },
  { alpha2Code: 'fo', country: 'Faroe Islands (Føroyar)', dialCode: '298' },
  { alpha2Code: 'fj', country: 'Fiji', dialCode: '679' },
  { alpha2Code: 'fi', country: 'Finland (Suomi)', dialCode: '358' },
  { alpha2Code: 'fr', country: 'France', dialCode: '33' },
  {
    alpha2Code: 'gf',
    country: 'French Guiana (Guyane française)',
    dialCode: '594',
  },
  {
    alpha2Code: 'pf',
    country: 'French Polynesia (Polynésie française)',
    dialCode: '689',
  },
  { alpha2Code: 'ga', country: 'Gabon', dialCode: '241' },
  { alpha2Code: 'gm', country: 'Gambia', dialCode: '220' },
  { alpha2Code: 'ge', country: 'Georgia (საქართველო)', dialCode: '995' },
  { alpha2Code: 'de', country: 'Germany (Deutschland)', dialCode: '49' },
  { alpha2Code: 'gh', country: 'Ghana (Gaana)', dialCode: '233' },
  { alpha2Code: 'gi', country: 'Gibraltar', dialCode: '350' },
  { alpha2Code: 'gr', country: 'Greece (Ελλάδα)', dialCode: '30' },
  {
    alpha2Code: 'gl',
    country: 'Greenland (Kalaallit Nunaat)',
    dialCode: '299',
  },
  { alpha2Code: 'gd', country: 'Grenada', dialCode: '1473' },
  { alpha2Code: 'gp', country: 'Guadeloupe', dialCode: '590' },
  { alpha2Code: 'gu', country: 'Guam', dialCode: '1671' },
  { alpha2Code: 'gt', country: 'Guatemala', dialCode: '502' },
  { alpha2Code: 'gn', country: 'Guinea (Guinée)', dialCode: '224' },
  {
    alpha2Code: 'gw',
    country: 'Guinea-Bissau (Guiné Bissau)',
    dialCode: '245',
  },
  { alpha2Code: 'gy', country: 'Guyana', dialCode: '592' },
  { alpha2Code: 'ht', country: 'Haiti', dialCode: '509' },
  { alpha2Code: 'hn', country: 'Honduras', dialCode: '504' },
  { alpha2Code: 'hk', country: 'Hong Kong (香港)', dialCode: '852' },
  { alpha2Code: 'hu', country: 'Hungary (Magyarország)', dialCode: '36' },
  { alpha2Code: 'is', country: 'Iceland (Ísland)', dialCode: '354' },
  { alpha2Code: 'in', country: 'India (भारत)', dialCode: '91' },
  { alpha2Code: 'id', country: 'Indonesia', dialCode: '62' },
  { alpha2Code: 'ir', country: 'Iran (ایران‬‎)', dialCode: '98' },
  { alpha2Code: 'iq', country: 'Iraq (العراق‬‎)', dialCode: '964' },
  { alpha2Code: 'ie', country: 'Ireland', dialCode: '353' },
  {
    alpha2Code: 'il',
    country: 'Israel (ישראל‬‎&#x202C;&lrml)',
    dialCode: '972',
  },
  { alpha2Code: 'it', country: 'Italy (Italia)', dialCode: '39' },
  { alpha2Code: 'jm', country: 'Jamaica', dialCode: '1876' },
  { alpha2Code: 'jp', country: 'Japan (日本)', dialCode: '81' },
  { alpha2Code: 'jo', country: 'Jordan (الأردن‬‎)', dialCode: '962' },
  { alpha2Code: 'kz', country: 'Kazakhstan (Казахстан)', dialCode: '7' },
  { alpha2Code: 'ke', country: 'Kenya', dialCode: '254' },
  { alpha2Code: 'ki', country: 'Kiribati', dialCode: '686' },
  { alpha2Code: 'kw', country: 'Kuwait (الكويت‬‎‬‎)', dialCode: '965' },
  { alpha2Code: 'kg', country: 'Kyrgyzstan (Кыргызстан)', dialCode: '996' },
  { alpha2Code: 'la', country: 'Laos PDR (ລາວ)', dialCode: '856' },
  { alpha2Code: 'lv', country: 'Latvia (Latvija)', dialCode: '371' },
  { alpha2Code: 'lb', country: 'Lebanon (لبنان‬‎)', dialCode: '961' },
  { alpha2Code: 'ls', country: 'Lesotho', dialCode: '266' },
  { alpha2Code: 'lr', country: 'Liberia', dialCode: '231' },
  { alpha2Code: 'ly', country: 'Libya (ليبيا‬‎)', dialCode: '218' },
  { alpha2Code: 'li', country: 'Liechtenstein', dialCode: '423' },
  { alpha2Code: 'lt', country: 'Lithuania (Lietuva)', dialCode: '370' },
  { alpha2Code: 'lu', country: 'Luxembourg', dialCode: '352' },
  { alpha2Code: 'mo', country: 'Macau (澳門)', dialCode: '853' },
  {
    alpha2Code: 'mk',
    country: 'Macedonia (FYROM) (Македонија)',
    dialCode: '389',
  },
  { alpha2Code: 'mg', country: 'Madagascar (Madagasikara)', dialCode: '261' },
  { alpha2Code: 'mw', country: 'Malawi', dialCode: '265' },
  { alpha2Code: 'my', country: 'Malaysia', dialCode: '60' },
  { alpha2Code: 'mv', country: 'Maldives', dialCode: '960' },
  { alpha2Code: 'ml', country: 'Mali', dialCode: '223' },
  { alpha2Code: 'mt', country: 'Malta', dialCode: '356' },
  { alpha2Code: 'mh', country: 'Marshall Islands', dialCode: '692' },
  { alpha2Code: 'mq', country: 'Martinique', dialCode: '596' },
  { alpha2Code: 'mr', country: 'Mauritania (موريتانيا‬‎)', dialCode: '222' },
  { alpha2Code: 'mu', country: 'Mauritius (Moris)', dialCode: '230' },
  { alpha2Code: 'mx', country: 'Mexico (México)', dialCode: '52' },
  { alpha2Code: 'fm', country: 'Micronesia', dialCode: '691' },
  { alpha2Code: 'md', country: 'Moldova (Republica Moldova)', dialCode: '373' },
  { alpha2Code: 'mc', country: 'Monaco', dialCode: '377' },
  { alpha2Code: 'mn', country: 'Mongolia (Монгол)', dialCode: '976' },
  { alpha2Code: 'me', country: 'Montenegro (Crna Gora)', dialCode: '382' },
  { alpha2Code: 'ms', country: 'Montserrat', dialCode: '1664' },
  { alpha2Code: 'ma', country: 'Morocco (المغرب‬‎)', dialCode: '212' },
  { alpha2Code: 'mz', country: 'Mozambique (Moçambique)', dialCode: '258' },
  { alpha2Code: 'mm', country: 'Myanmar (Burma) (မြန်မာ)', dialCode: '95' },
  { alpha2Code: 'na', country: 'Namibia (Namibië)', dialCode: '264' },
  { alpha2Code: 'np', country: 'Nepal (नेपाल)', dialCode: '977' },
  { alpha2Code: 'nl', country: 'Netherlands (Nederland)', dialCode: '31' },
  {
    alpha2Code: 'nc',
    country: 'New Caledonia (Nouvelle-Calédonie)',
    dialCode: '687',
  },
  { alpha2Code: 'nz', country: 'New Zealand', dialCode: '64' },
  { alpha2Code: 'ni', country: 'Nicaragua', dialCode: '505' },
  { alpha2Code: 'ne', country: 'Niger (Nijar)', dialCode: '227' },
  { alpha2Code: 'ng', country: 'Nigeria', dialCode: '234' },
  { alpha2Code: 'nu', country: 'Niue', dialCode: '683' },
  { alpha2Code: 'nf', country: 'Norfolk Island', dialCode: '672' },
  { alpha2Code: 'no', country: 'Norway (Norge)', dialCode: '47' },
  { alpha2Code: 'om', country: 'Oman (عُمان‬‎)', dialCode: '968' },
  { alpha2Code: 'pk', country: 'Pakistan (پاکستان‬‎)', dialCode: '92' },
  { alpha2Code: 'pw', country: 'Palau', dialCode: '680' },
  {
    alpha2Code: 'ps',
    country: 'Palestine (Palestinian Territory) (فلسطين‬‎)',
    dialCode: '970',
  },
  { alpha2Code: 'pa', country: 'Panama (Panamá)', dialCode: '507' },
  { alpha2Code: 'pg', country: 'Papua New Guinea', dialCode: '675' },
  { alpha2Code: 'py', country: 'Paraguay', dialCode: '595' },
  { alpha2Code: 'pe', country: 'Peru (Perú)', dialCode: '51' },
  { alpha2Code: 'ph', country: 'Philippines', dialCode: '63' },
  { alpha2Code: 'pl', country: 'Poland (Polska)', dialCode: '48' },
  { alpha2Code: 'pt', country: 'Portugal', dialCode: '351' },
  { alpha2Code: 'pr', country: 'Puerto Rico', dialCode: '1' },
  { alpha2Code: 'qa', country: 'Qatar (قطر‬‎)', dialCode: '974' },
  { alpha2Code: 're', country: 'Reunion/Mayotte', dialCode: '262' },
  { alpha2Code: 'ro', country: 'Romania (România)', dialCode: '40' },
  { alpha2Code: 'ru', country: 'Russia (Россия)', dialCode: '7' },
  { alpha2Code: 'rw', country: 'Rwanda', dialCode: '250' },
  { alpha2Code: 'ws', country: 'Samoa', dialCode: '685' },
  { alpha2Code: 'sm', country: 'San Marino', dialCode: '378' },
  {
    alpha2Code: 'st',
    country: 'Sao Tome and Principe (São Tomé and Príncipe) (São Tomé e Príncipe)',
    dialCode: '239',
  },
  {
    alpha2Code: 'sa',
    country: 'Saudi Arabia (‫المملكة العربية السعودية‬‎)',
    dialCode: '966',
  },
  { alpha2Code: 'sn', country: 'Senegal (Sénégal)', dialCode: '221' },
  { alpha2Code: 'rs', country: 'Serbia (Србија)', dialCode: '381' },
  { alpha2Code: 'sc', country: 'Seychelles', dialCode: '248' },
  { alpha2Code: 'sl', country: 'Sierra Leone', dialCode: '232' },
  { alpha2Code: 'sg', country: 'Singapore', dialCode: '65' },
  { alpha2Code: 'sk', country: 'Slovakia (Slovensko)', dialCode: '421' },
  { alpha2Code: 'sb', country: 'Solomon Islands', dialCode: '677' },
  { alpha2Code: 'so', country: 'Somalia (Soomaaliya)', dialCode: '252' },
  { alpha2Code: 'za', country: 'South Africa', dialCode: '27' },
  {
    alpha2Code: 'kr',
    country: 'Republic Of Korea (대한민국) (South Korea)',
    dialCode: '82',
  },
  { alpha2Code: 'es', country: 'Spain (España)', dialCode: '34' },
  { alpha2Code: 'lk', country: 'Sri Lanka (ශ්‍රී ලංකාව)', dialCode: '94' },
  {
    alpha2Code: 'kn',
    country: 'St Kitts and Nevis (Saint Kitts and Nevis)',
    dialCode: '1869',
  },
  { alpha2Code: 'lc', country: 'St Lucia (Saint Lucia)', dialCode: '1758' },
  {
    alpha2Code: 'pm',
    country: 'St Pierre and Miquelon (St Pierre and Miquelon) (Saint-Pierre-et-Miquelon)',
    dialCode: '508',
  },
  {
    alpha2Code: 'vc',
    country: 'St Vincent Grenadines (Saint Vincent and the Grenadines)',
    dialCode: '1784',
  },
  { alpha2Code: 'sd', country: 'Sudan (السودان‬‎)', dialCode: '249' },
  { alpha2Code: 'sr', country: 'Suriname', dialCode: '597' },
  { alpha2Code: 'sz', country: 'Swaziland', dialCode: '268' },
  { alpha2Code: 'se', country: 'Sweden (Sverige)', dialCode: '46' },
  { alpha2Code: 'ch', country: 'Switzerland (Schweiz)', dialCode: '41' },
  { alpha2Code: 'sy', country: 'Syria (سوريا‬‎)', dialCode: '963' },
  { alpha2Code: 'tw', country: 'Taiwan (台灣)', dialCode: '886' },
  { alpha2Code: 'tj', country: 'Tajikistan', dialCode: '992' },
  { alpha2Code: 'tz', country: 'Tanzania', dialCode: '255' },
  { alpha2Code: 'th', country: 'Thailand (ไทย)', dialCode: '66' },
  { alpha2Code: 'tg', country: 'Togo', dialCode: '228' },
  { alpha2Code: 'to', country: 'Tonga', dialCode: '676' },
  { alpha2Code: 'tt', country: 'Trinidad and Tobago', dialCode: '1868' },
  { alpha2Code: 'tn', country: 'Tunisia (تونس‬‎)', dialCode: '216' },
  { alpha2Code: 'tr', country: 'Turkey (Türkiye)', dialCode: '90' },
  { alpha2Code: 'tm', country: 'Turkmenistan', dialCode: '993' },
  { alpha2Code: 'tc', country: 'Turks and Caicos Islands', dialCode: '1649' },
  { alpha2Code: 'tv', country: 'Tuvalu', dialCode: '688' },
  { alpha2Code: 'ug', country: 'Uganda', dialCode: '256' },
  { alpha2Code: 'ua', country: 'Ukraine (Україна)', dialCode: '380' },
  {
    alpha2Code: 'ae',
    country: 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)',
    dialCode: '971',
  },
  { alpha2Code: 'gb', country: 'United Kingdom', dialCode: '44' },
  { alpha2Code: 'us', country: 'United States', dialCode: '1' },
  { alpha2Code: 'uy', country: 'Uruguay', dialCode: '598' },
  { alpha2Code: 'uz', country: 'Uzbekistan (Oʻzbekiston)', dialCode: '998' },
  { alpha2Code: 'vu', country: 'Vanuatu', dialCode: '678' },
  { alpha2Code: 've', country: 'Venezuela', dialCode: '58' },
  { alpha2Code: 'vn', country: 'Vietnam (Việt Nam)', dialCode: '84' },
  { alpha2Code: 'vg', country: 'Virgin Islands, British', dialCode: '1284' },
  { alpha2Code: 'vi', country: 'Virgin Islands, U.S.', dialCode: '1340' },
  {
    alpha2Code: 'wf',
    country: 'Wallis and Futuna (Wallis-et-Futuna)',
    dialCode: '681',
  },
  { alpha2Code: 'ye', country: 'Yemen (اليمن‬‎)', dialCode: '967' },
  { alpha2Code: 'zm', country: 'Zambia', dialCode: '260' },
  { alpha2Code: 'zw', country: 'Zimbabwe', dialCode: '263' },
];
